export const FEEDS = [
    {
        "hash_id": "e04qnsow-1",
        "author_name": "Hiral Goyal",
        "content": "A 1962 Ferrari 250 GTO fetched $51.7 million (₹430 crore), becoming the second-most expensive car ever auctioned, Sotheby's said. The car finished second in 1,000-km endurance race on German Nürburgring Nordschleife circuit in 1962 and also competed in 24 Hours of Le Mans that year. Mercedes 300 SLR Uhlenhaut Coupe is the most expensive car ever sold at $143 million.",
        "source_url": "https://www.news18.com/amp/auto/iconic-1962-ferrari-250-gto-secures-second-spot-in-auction-history-f-hes-staggering-51-7-million-8661356.html?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
        "source_name": "News18",
        "title": "1962 Ferrari sells for ₹430 crore, becomes 2nd most expensive car ever auctioned",
        "important": false,
        "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/14_tue/img_1699943392050_886.jpg?",
        "shortened_url": "https://shrts.in/sqL5R",
        "tenant": "ENGLISH",
        "position_start_time": "1970-01-01T00:00:00Z",
        "position_expire_time": "2023-11-15T06:31:52.367Z",
    },
    {
        "hash_id": "loatav1v-1",
        "author_name": "Ashley Paul",
        "content": "Dabur Group Chairman Mohit Burman and Director Gaurav Burman are among 31 accused named in an FIR filed by Mumbai Police in the Mahadev betting app case, India Today reported. The FIR was filed on social activist Prakash Bankar's complaint. According to Bankar's statement, Mohit and Gaurav had links to one of the bookies for match fixing in cricket leagues.",
        "source_url": "https://www.news18.com/amp/india/mahadev-betting-app-case-dabur-group-bosses-among-31-named-in-mumbai-police-fir-8661359.html?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
        "source_name": "News18",
        "title": "Dabur Chairman, Director named in Mahadev app case FIR: Report",
        "important": false,
        "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/14_tue/img_1699943534810_403.jpg?",
        "shortened_url": "https://shrts.in/2Vakk",
        "score": 800,
        "position_start_time": "1970-01-01T00:00:00Z",
        "position_expire_time": "2023-11-15T06:39:40.838Z",   
    },
    {
        "hash_id": "stc1he2d-1",
        "author_name": "Subhangi Singh",
        "content": "At least three people of a family died, while over six people were injured after a fire broke out at a shop located in Kendua market in Jharkhand's Dhanbad. The fire spread so fast that it engulfed the shop owner's house located on the upper floor, a fire official said. The shopkeeper's sister, mother and daughter died in the incident.",
        "source_url": "https://www.aninews.in/news/national/general-news/jharkhand-3-dead-several-injured-after-fire-breaks-out-in-dhanbad-market20231114110852/?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
        "source_name": "ANI News",
        "title": "3 of a family die after fire breaks out at a shop in Jharkhand",
        "important": true,
        "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/14_tue/img_1699941796933_146.jpg?",
        "shortened_url": "https://shrts.in/FY7ik",
        "score": 800,
        "position_start_time": "1970-01-01T00:00:00Z",
        "position_expire_time": "2023-11-15T06:33:30.627Z",
    },
    {
        "hash_id": "o49iqypp-1",
        "author_name": "Medhaa Gupta",
        "content": "Delhi on Monday recorded its coldest night of the season so far as the minimum temperature dropped to 11.8°C, which is two notches below normal, as per the national capital's Regional Meteorological Centre. The maximum temperature recorded was 27.3°C, it stated. This comes as the national capital reported real-time AQI of over 900 in some locations on the same day. ",
        "source_url": "https://www.news18.com/amp/india/weather-updates-mumbai-delhi-air-pollution-news-aqi-today-8661208.html?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
        "source_name": "News18",
        "title": "Delhi records coldest night of the season at 11.8°C",
        "important": true,
        "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/14_tue/img_1699941348631_601.jpg?",
        "shortened_url": "https://shrts.in/GC9kJ",
        "score": 800,
        "position_start_time": "1970-01-01T00:00:00Z",
        "position_expire_time": "2023-11-15T05:59:59.324Z",   
    },
    {
        "hash_id": "uwzl7onl-1",
        "author_name": "Medhaa Gupta",
        "content": "Six people were killed after a car they were travelling in rammed into a parked truck in Uttar Pradesh's Muzaffarnagar on Tuesday morning. A video of the damaged car has surfaced online. The deceased were going to Haridwar from Delhi. The police and rescue workers used a crane to retrieve the deceased's bodies which were trapped under truck.",
        "source_url": "https://news.abplive.com/states/up-uk/6-killed-in-car-truck-collision-in-up-s-muzaffarnagar-1642590/amp?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
        "source_name": "ABP Live",
        "title": "6 dead as car rams into parked truck in UP, clip shows damaged car",
        "important": true,
        "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/14_tue/img_1699934303052_710.jpg?",
        "shortened_url": "https://shrts.in/auj6y",
        "score": 800,
        "position_start_time": "1970-01-01T00:00:00Z",
        "position_expire_time": "2023-11-15T06:15:29.787Z",   
    },
    {
        "hash_id": "uhsqtqqn-1",
        "author_name": "Shalini Ojha",
        "content": "After Israeli PM Benjamin Netanyahu called Palestinians \"collateral damage\" in the ongoing Israel-Hamas war, actor Mark Ruffalo asked him to have some compassion. \"They are Palestinians...not buildings or roads or things, they are human beings and so are the hostages whose lives you may also be destroying,\" he said. Netanyahu said Israel is doing everything to target the terrorists. ",
        "source_url": "https://www.ndtv.com/world-news/have-some-compassion-mark-ruffalos-response-to-israeli-pm-calling-palestinians-collateral-damage-4572253/amp/1?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
        "source_name": "NDTV",
        "title": "Have some compassion: Mark Ruffalo after Israel PM calls Palestinians 'collateral damage'",
        "important": false,
        "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/14_tue/img_1699941819054_857.jpg?",
        "shortened_url": "https://shrts.in/mM2ew",
        "score": 800,
        "position_start_time": "1970-01-01T00:00:00Z",
        "position_expire_time": "2023-11-15T06:13:10.617Z", 
    },
    {
        "hash_id": "9xt05ruk-2",
        "author_name": "Nidhi Sinha",
        "content": "A woman died and many were injured after a massive fire erupted at a residential building in Delhi's Shakarpur on the intervening night of Monday and Tuesday. Delhi Fire Services Director Atul Garg said that while five people jumped off the building, 26 people and two pets were rescued. Fire started in a car parked in the building, he added.",
        "source_url": "https://www.youtube.com/watch?utm_campaign=fullarticle&v=NnegjN310YU&utm_medium=referral&utm_source=inshorts",
        "source_name": "YouTube",
        "title": "Woman dies, 5 people jump off building as fire erupts in Delhi",
        "important": true,
        "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/14_tue/img_1699940395523_178.jpg?",
        "shortened_url": "https://shrts.in/ABBBi",
        "video_url": "https://www.youtube.com/watch?v=NnegjN310YU",
        "score": 800,
        "position_start_time": "1970-01-01T00:00:00Z",
        "position_expire_time": "2023-11-15T06:10:45.397Z",   
    },
    {
        "hash_id": "4v12m8gd-1",
        "author_name": "Subhangi Singh",
        "content": "After receiving criticism over his \"how can Goddess Lakshmi be born with four hands?\", SP's Swami Prasad Maurya said, \"I had not spoken about four arms alone, I also spoke about eight, 10, 1,000 arms.\" \"No such child has ever been born in country. If it does happen, I challenge them to tell me, I will accept it,\" he added.",
        "source_url": "https://www.siasat.com/sp-leader-swami-maurya-clarifies-remarks-on-goddess-lakshmi-2871196/?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
        "source_name": "The Siasat Daily",
        "title": "Didn't speak about 4 only but 8, 10, 1,000 arms: Maurya on Goddess Laxmi remark",
        "important": false,
        "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/14_tue/img_1699939676231_145.jpg?",
        "shortened_url": "https://shrts.in/JEmkT",
        "video_url": "https://www.youtube.com/watch?v=NnegjN310YU",
        "score": 800,
        "position_start_time": "1970-01-01T00:00:00Z",
        "position_expire_time": "2023-11-15T06:02:54.932Z", 
    },
    {
        "hash_id": "av5bdfxc-1",
        "author_name": "Shalini Ojha",
        "content": "The Madhya Pradesh High Court recently said that abusing someone using a caste name inside a staffroom isn't an offence under the SC/ST Act since the staffroom isn't a public place. The court also quashed criminal proceedings pending against the accused since 2010. The complainant alleged remarks based on caste were used during a meeting in the school staffroom. \n",
        "source_url": "https://twitter.com/news24tvchannel/status/1724278154372751579?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
        "source_name": "News24",
        "title": "Abusing with caste name in staffroom not an offence as it isn't a public place: MP HC",
        "important": false,
        "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/14_tue/img_1699939791498_242.jpg?",
        "shortened_url": "https://shrts.in/j7Sby",
        "video_url": "https://www.youtube.com/watch?v=NnegjN310YU",
        "score": 800,
        "position_start_time": "1970-01-01T00:00:00Z",
        "position_expire_time": "2023-11-15T05:34:22.048Z",
    },
    {
        "hash_id": "cs7vyclv-1",
        "author_name": "Arshiya Chopra",
        "content": "At UN Human Rights Council Review meeting, India recommended Canada to take measures preventing attacks on religious places and effectively address hate speech. India's Mohammed Hussain said, \"India recommends...Canada [to] further, strengthen the domestic framework to prevent misuse of freedom of expression, for inciting violence and disallow activities of groups that are promoting extremism.\"",
        "source_url": "https://www.aninews.in/news/world/europe/india-recommends-canada-to-prevent-attacks-on-places-of-worship-address-hate-speech20231114064344/?utm_campaign=fullarticle&utm_medium=referral&utm_source=inshorts",
        "source_name": "ANI News",
        "title": "India recommends Canada to prevent attack on religious places, address hate speech",
        "important": false,
        "image_url": "https://nis-gs.pix.in/inshorts/images/v1/variants/jpg/m/2023/11_nov/14_tue/img_1699938969901_37.jpg?",
        "shortened_url": "https://shrts.in/sTH1s",
        "video_url": "https://www.youtube.com/watch?v=NnegjN310YU",
        "score": 800,
        "position_start_time": "1970-01-01T00:00:00Z",
        "position_expire_time": "2023-11-15T05:24:59.173Z",
    }
];

export const NAV_LINKS = [
    {'href': '/', 'label': 'Home'},
    {'href': '/', 'label': 'About'},
    {'href': '/', 'label': 'Categories'},
    {'href': '/', 'label': 'News'},
    {'href': '/', 'label': 'Article'},
    {'href': '/', 'label': 'Contact'},
];